# Generated by Django 5.0.6 on 2024-06-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_connection_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='password',
            new_name='ssh_pass',
        ),
    ]
