# Generated by Django 5.0.6 on 2024-06-19 20:11

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType

from api.models import Source

def create_default_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    content_type = ContentType.objects.get_for_model(Source)

    groups_permissions = {
        'Dev': ['api.view_source','api.view_connection'],
        'Manager': ['api.add_source','api.change_source','api.view_source','api.delete_source','api.add_connection','api.change_connection','api.view_connection','api.delete_connection'],
    }
    
    for group_name, permissions_list in groups_permissions.items():
        group, created = Group.objects.get_or_create(name=group_name)
        permissions = Permission.objects.filter(codename__in=permissions_list)
        group.permissions.add(*permissions)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_password_connection_ssh_pass'),
    ]

    operations = [
        migrations.RunPython(create_default_groups),
    ]
