# Generated by Django 5.0.6 on 2024-06-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_organization_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='ssh_pass',
            new_name='password',
        ),
    ]
