# Generated by Django 5.0.6 on 2024-06-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_host_connection_ssh_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='file_name',
            field=models.CharField(default='empty', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='file_path',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
