# Generated by Django 5.0.6 on 2024-06-25 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usersource'),
        ('api', '0004_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmanuser',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.organization'),
            preserve_default=False,
        ),
    ]
