# Generated by Django 5.0.6 on 2024-06-26 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_logmanuser_organization'),
        ('api', '0005_organization_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmanuser',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.organization'),
        ),
    ]
