# Generated by Django 5.0.6 on 2024-07-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_logmanuser_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmanuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
